### PR TITLE
Add SSH proxy and Viper for configuration pluss Travis build fixed

### LINKED ISSUE #22: mitm ssh connections
This looks interesting: https://github.com/dutchcoders/sshproxy

### PR DESCRIPTION
**Pull request by furusiyya**
#22 Solved

### CODE REVIEW

File: glutton.go [hunk 1]
```diff
@@ -60,24 +59,28 @@ func (g *Glutton) makeID() error {
 }
 
 func (g *Glutton) addServers() {
+	p1 := uint(g.conf.GetInt("proxy_tcp"))
```
Comment (glaslos) [inline glutton.go]: What does `p1` stand for?

File: proxy_ssh.go [hunk 2]
```diff
@@ -0,0 +1,287 @@
...
+	// Shot to validating private bytes
+	_, err = ssh.ParsePrivateKey(RSA_Key)
+	if err != nil {
+		s.logger.Error(errors.Wrap(err, "ssh.prxy"))
+		return nil, err
+	}
+	return RSA_Key, nil
+}
+
+func interpreter(msg string, err error) error {
```
Comment (glaslos) [inline proxy_ssh.go]: Not sure about the name of this function.

File: proxy_ssh.go [hunk 3]
```diff
@@ -0,0 +1,287 @@
...
+	return errors.New(fmt.Sprintf("%s  %s\n", msg, err))
+}
+
+func (rs *ReadSession) Read(p []byte) (n int, err error) {
```
Comment (glaslos) [inline proxy_ssh.go]: Why exported?

File: proxy_ssh.go [hunk 4]
```diff
@@ -0,0 +1,287 @@
...
+		go rs.collector((rs.n + n))
+		rs.n = 0
+	} else {
+		rs.buffer.Write(p[:n])
+		rs.n += n
+	}
+	return n, err
+}
+
+func (rs *ReadSession) String() string {
```
Comment (glaslos) [inline proxy_ssh.go]: Why exported?

File: proxy_ssh.go [hunk 5]
```diff
@@ -0,0 +1,287 @@
...
+	return rs.buffer.String()
+}
+
+func (rs *ReadSession) Close() error {
```
Comment (glaslos) [inline proxy_ssh.go]: Why exported?

File: proxy_ssh.go (hunk 2 above)
Comment (furusiyya) [inline proxy_ssh.go]: this function actually append additional information to error to it more descriptive. Interpreter is one who who explains. 
Your opinion?

Comment (glaslos) [inline proxy_ssh.go]: `formatErrorMsg`?

File: proxy_ssh.go (hunk 3 above)
Comment (furusiyya) [inline proxy_ssh.go]: How I can pass buffer to Read in other way?

Comment (glaslos) [inline proxy_ssh.go]: Where is this used? Same package?

File: proxy_ssh.go (hunk 4 above)
Comment (furusiyya) [inline proxy_ssh.go]: Again to pass buffer. Well another way is to declare buffer globally.

File: proxy_ssh.go (hunk 2 above)
Comment (furusiyya) [inline proxy_ssh.go]: sounds good :)

File: proxy_ssh.go (hunk 3 above)
Comment (furusiyya) [inline proxy_ssh.go]: Yes same package, another thing I need to wrap a ssh channel to custom type with io.Reader, so that I could look into io.Copy. : https://github.com/mushorg/glutton/pull/51/files#diff-69a47fd69d5b7a436ed294d80b5228fcR107

File: proxy_ssh.go [hunk 6]
```diff
@@ -0,0 +1,287 @@
...
+		}()
+
+		var wrappedServerChan io.ReadCloser = sshServerChan
+		var wrappedClientChan io.ReadCloser = sshClientChan
+
+		defer wrappedServerChan.Close()
+		defer wrappedClientChan.Close()
+
+		if s.wrapFn != nil {
+			wrappedClientChan, err = s.wrapFn(serverConn, sshClientChan)
```
Comment (furusiyya) [inline proxy_ssh.go]: Instead of passing original channel I am passing custom struct with io.Reader implemented.

File: proxy_ssh.go [hunk 7]
```diff
@@ -0,0 +1,287 @@
...
+type SSHProxy struct {
+	logger     *log.Logger
+	config     *ssh.ServerConfig
+	callbackFn func(c ssh.ConnMetadata) (*ssh.Client, error)
+	wrapFn     func(c ssh.ConnMetadata, r io.ReadCloser) (io.ReadCloser, error)
+	closeFn    func(c ssh.ConnMetadata) error
+	reader     *ReadSession
+}
+
+type ReadSession struct {
```
Comment (furusiyya) [inline proxy_ssh.go]: I am not sure, You are asking about ReadSession? why this type is exported?

File: glide.lock [hunk 8]
```diff
@@ -62,6 +85,25 @@ imports:
   version: 0208149b40d863d2c1a2f8fe5753096a9cf2cc8b
 - name: github.com/Sirupsen/logrus
```
Comment (glaslos) [inline glide.lock]: We should import logrus only once.

Comment (furusiyya) [inline glide.lock]: hmm, so  I need to implement a logger interface to do this. I was also thinking to change architecture a little bit. Well I will made a separate PR for this.
